plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ruangfafa.popupshield'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ruangfafa.popupshield'
        minSdk 23
        targetSdk 33
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
